spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cqqk?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tuandui2020
  redis:
    host: 127.0.0.1
    port: 6379
  activiti:
    database-schema-update: true # 对所有表更新操作，如不存在则创建
    history-level: full # 保存历史数据的最高级别
    db-history-used: true # 使用历史表
    check-process-definitions: true # 校验流程文件
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      #key-prefix: CACHE_
      use-key-prefix: true
      cache-null-values: true

server:
  port: 8099

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

logging:
  level:
    com.aphea.cqqksrv: debug

